version: "3"
services:
  python-dev-env:
    build: .
    restart: always
    container_name: 'python-dev-env'
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - python-dev-env:/app
    networks:
      - local

  postgres:
    image: postgres:13.3
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - '5432'
    ports:
      - "5432:5432"
    tty: true
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - local

  redis:
    image: "redis:latest"
    restart: always
    container_name: "redis"
    ports:
      - "6379:6379"
    tty: true
    volumes:
      - redis:/data
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
    python-dev-env:
    database:
    redis:
